# Generated by Django 6.1 on 2026-09-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_daily_quota',
            field=models.IntegerField(default=5, verbose_name='حداکثر سهمیه روزانه'),
        ),
    ]
