# Generated by Django 6.0.6 on 2026-08-30 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='شناسه مهمان')),
                ('daily_usage', models.IntegerField(default=0, verbose_name='استفاده امروز')),
                ('last_usage_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ آخرین استفاده')),
            ],
            options={
                'verbose_name': 'استفاده کاربر مهمان',
                'verbose_name_plural': 'استفاده کاربران مهمان',
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(choices=[('mistral', 'Mistral AI')], default='mistral', max_length=50, verbose_name='ارائه\u200cدهنده')),
                ('model_name', models.CharField(default='mistral-small-2506', max_length=100, verbose_name='نام مدل هوش مصنوعی')),
                ('api_key', models.CharField(max_length=255, verbose_name='کلید API')),
                ('priority_order', models.IntegerField(default=1, verbose_name='ترتیب اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تنظیمات ارائه\u200cدهنده هوش مصنوعی',
                'verbose_name_plural': 'تنظیمات ارائه\u200cدهندگان هوش مصنوعی',
                'ordering': ['priority_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TranslationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='شناسه تسک')),
                ('identifier', models.CharField(max_length=255, verbose_name='شناسه مهمان/IP')),
                ('filename', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('char_count', models.IntegerField(default=0, verbose_name='تعداد کاراکتر')),
                ('target_lang', models.CharField(default='fa', max_length=10, verbose_name='زبان مقصد')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'خطا در پردازش')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('progress', models.IntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('current_chunk', models.IntegerField(default=0, verbose_name='بخش جاری')),
                ('total_chunks', models.IntegerField(default=0, verbose_name='مجموع بخش\u200cها')),
                ('result_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر فایل خروجی')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='متن خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تسک ترجمه',
                'verbose_name_plural': 'تسک\u200cهای ترجمه',
                'ordering': ['-created_at'],
            },
        ),
    ]
