# Generated by Django 6.0.6 on 2026-08-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerconfig',
            name='model_name',
            field=models.CharField(default='gemini/gemini-3.6-flash', max_length=100, verbose_name='نام مدل هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='providerconfig',
            name='provider_name',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('mistral', 'Mistral AI')], default='gemini', max_length=50, verbose_name='ارائه\u200cدهنده'),
        ),
    ]
