# Generated by Django 6.0.6 on 2026-08-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_alter_providerconfig_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationtask',
            name='provider_used',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='مدل هوش مصنوعی استفاده\u200cشده'),
        ),
    ]
