# Generated by Django 6.0.6 on 2026-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_translationtask_provider_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationtask',
            name='provider_used',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='مدل\u200cهای هوش مصنوعی استفاده\u200cشده'),
        ),
    ]
